USE test_neu_registrar;

DROP PROCEDURE IF EXISTS select_ssrmeet;

DELIMITER //

CREATE PROCEDURE select_ssrmeet()
BEGIN
	SELECT SSRMEET_TERM_CODE AS 'termCode', SSRMEET_CRN AS 'crn', SSRMEET_START_DATE AS 'startDate', SSRMEET_END_DATE AS 'endDate',
		SSRMEET_BEGIN_TIME AS 'beginTime', SSRMEET_END_TIME AS 'endTime', SSRMEET_DAYS AS 'days'
    FROM ssrmeet;
END//

DELIMITER ;
